# Add the current directory to the module path
list(APPEND CMAKE_MODULE_PATH CMAKE_CURRENT_LIST_DIR)
message(STATUS ">>> Found Embedded SuperLoop at ${CMAKE_CURRENT_LIST_DIR}")
include(${CMAKE_CURRENT_LIST_DIR}/embedded-superloop.cmake)


# get_property(TARGET_ARCHITECTURES GLOBAL PROPERTY TARGET_ARCHITECTURES)
# set(TARGET_ARCHITECTURES ${TARGET_ARCHITECTURES} PARENT_SCOPE)
# message(STATUS "==> architecture targets: ${TARGET_ARCHITECTURES}")
# get_property(TARGET_BOARDS GLOBAL PROPERTY TARGET_BOARDS)
# set(TARGET_BOARDS ${TARGET_BOARDS} PARENT_SCOPE)
# message(STATUS "==> board targets: ${TARGET_BOARDS}")
# get_property(TARGET_UNIT_TESTS GLOBAL PROPERTY TARGET_UNIT_TESTS)
# set(TARGET_UNIT_TESTS ${TARGET_UNIT_TESTS} PARENT_SCOPE)
# message(STATUS "==> unit test targets: ${TARGET_UNIT_TESTS}")

# message(STATUS "--> BUILD_UNIT_TESTS=${BUILD_UNIT_TESTS}")
# message(STATUS "--> BUILD_DOCUMENTATION=${BUILD_DOCUMENTATION}")
# message(STATUS "--> BUILD_COVERAGE=${BUILD_COVERAGE}")
# message(STATUS "--> BUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}")
# message(STATUS "--> BUILD_CROSS_TARGET=${BUILD_CROSS_TARGET}")
